
site_name: Satellite Temp
site_url: https://sat_temp.com/
nav:
  - Home: home.md
  - Mechanics: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



theme: readthedocs
